/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.VehiculoController;
import controller.VehiculoPersonaController;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;

/**
 *
 * @author JETTSUSHD
 */
public class viewCrearVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form viewCrearVehiculo
     */
    public viewCrearVehiculo() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        // Pasamos la tabla como parametroesté pasando correctamente al controlador
        VehiculoPersonaController vehiculoPersonaController = new VehiculoPersonaController(this);

        vehiculoPersonaController.mostrarcbMarcaEnVistaCrearVehiculo();
        setTitle("Crear vehiculos");
        keyBinding();
    }

    public JComboBox<String> getcbModelo() {
        return cbModelo;
    }

    public JComboBox<String> getcbMarca() {
        return cbMarca;
    }

    public void keyBinding() {
        JRootPane rootpane = getRootPane();

        // Acción para cerrar la ventana con ESCAPE
        Action cerrarAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };

        // Acción para aumentar el tamaño de la ventana con CTRL + 
        Action aumentarTamano = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Dimension tamanoActual = getSize();
                setSize(tamanoActual.width + 30, tamanoActual.height + 10);
            }
        };

        // Acción para disminuir el tamaño de la ventana con CTRL + -
        Action disminuirTamano = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Dimension tamanoActual = getSize();
                setSize(tamanoActual.width - 30, tamanoActual.height - 10);
            }
        };

        //añadir keybinding para la tecla escape cierre programa
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "CERRAR");
        rootpane.getActionMap().put("CERRAR", cerrarAction);

        //añadir keybinding para la tecla crtl + aumente el tamaño de la ventana
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_PLUS, KeyEvent.CTRL_DOWN_MASK), "AUMENTAR");
        rootpane.getActionMap().put("AUMENTAR", aumentarTamano);

        //añadir keybinding para la tecla crtl - disminuya el tamaño de la ventana
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_MINUS, KeyEvent.CTRL_DOWN_MASK), "DISMINUIR");
        rootpane.getActionMap().put("DISMINUIR", disminuirTamano);

        requestFocusInWindow();
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        bConfirmar = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lMatriculacion = new javax.swing.JLabel();
        lAnio = new javax.swing.JLabel();
        lMarca = new javax.swing.JLabel();
        lModelo = new javax.swing.JLabel();
        tfMatriculacion = new javax.swing.JTextField();
        tfAnio = new javax.swing.JTextField();
        cbModelo = new javax.swing.JComboBox<>();
        cbMarca = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        bConfirmar.setText("OK");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(bConfirmar);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel1.add(bCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lMatriculacion.setText("Matriculación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lMatriculacion, gridBagConstraints);

        lAnio.setText("Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lAnio, gridBagConstraints);

        lMarca.setText("Marca:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lMarca, gridBagConstraints);

        lModelo.setText("Modelo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lModelo, gridBagConstraints);

        tfMatriculacion.setPreferredSize(new java.awt.Dimension(160, 24));
        tfMatriculacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatriculacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 31, 8, 8);
        jPanel2.add(tfMatriculacion, gridBagConstraints);

        tfAnio.setPreferredSize(new java.awt.Dimension(160, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 31, 8, 8);
        jPanel2.add(tfAnio, gridBagConstraints);

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbModelo.setPreferredSize(new java.awt.Dimension(160, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(8, 31, 8, 8);
        jPanel2.add(cbModelo, gridBagConstraints);

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMarca.setPreferredSize(new java.awt.Dimension(160, 24));
        cbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 31, 8, 8);
        jPanel2.add(cbMarca, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        boolean esValido = true;

        // Tomo los datos que ingresó el usuario
        String matricula = tfMatriculacion.getText().trim();
        String anioStr = tfAnio.getText().trim();
        String modelo = (String) cbModelo.getSelectedItem();
        String marca = (String) cbMarca.getSelectedItem();

        // Valido que la matrícula no esté vacía, tenga exactamente 4 números y 3 letras
        if (matricula.isEmpty() || !matricula.matches("^[0-9]{4}[A-Za-z]{3}$")) {
            JOptionPane.showMessageDialog(
                    this,
                    "La matrícula debe contener exactamente 4 números seguidos de 3 letras (ejemplo: 1234ABC).",
                    "Error en la Matrícula",
                    JOptionPane.ERROR_MESSAGE
            );
            esValido = false;
        }

        // Verifico si la matrícula ya existe en el sistema
        if (esValido) {
            VehiculoController vehiculoController = new VehiculoController();
            if (vehiculoController.verificarMatriculaExiste(matricula)) {
                esValido = false; // Si existe, se muestra el mensaje en el método y no continúa
            }
        }

        // Valido que el año no esté vacío, tenga exactamente 4 dígitos y no contenga palabras peligrosas
        if (esValido && anioStr.matches(".*\\b(?i)(select|insert|drop|delete|update|alter|create|exec|union|historico|personas|vehiculos)\\b.*")) {
            JOptionPane.showMessageDialog(
                    this,
                    "El año no puede contener palabras reservadas como 'SELECT', 'INSERT', 'DROP', etc.",
                    "Error en el Año",
                    JOptionPane.ERROR_MESSAGE
            );
            esValido = false;
        }

        if (esValido) {
            if (anioStr.isEmpty() || !anioStr.matches("^[0-9]{4}$")) {
                JOptionPane.showMessageDialog(
                        this,
                        "El año debe ser un número de 4 dígitos.",
                        "Error en el Año",
                        JOptionPane.ERROR_MESSAGE
                );
                esValido = false;
            } else {
                int anioActual = Calendar.getInstance().get(Calendar.YEAR);
                int anio = Integer.parseInt(anioStr);
                if (anio < 1900 || anio > anioActual) {
                    JOptionPane.showMessageDialog(
                            this,
                            "El año debe estar entre 1900 y " + anioActual + ".",
                            "Error en el Año",
                            JOptionPane.ERROR_MESSAGE
                    );
                    esValido = false;
                }
            }
        }

        // Valido que el usuario haya seleccionado una marca y un modelo válidos
        if (esValido) {
            if (marca == null || marca.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar una marca válida.",
                        "Error en la Marca",
                        JOptionPane.ERROR_MESSAGE
                );
                esValido = false;
            } else if (modelo == null || modelo.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar un modelo válido.",
                        "Error en el Modelo",
                        JOptionPane.ERROR_MESSAGE
                );
                esValido = false;
            }
        }

        // Confirmo antes de guardar el vehículo
        if (esValido) {
            int respuesta = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de que desea agregar el vehículo?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            // Si el usuario dice que sí, guardo los datos
            if (respuesta == JOptionPane.YES_OPTION) {
                VehiculoController vehiculoController = new VehiculoController();
                vehiculoController.agregarVehiculo(matricula, Integer.parseInt(anioStr), modelo, marca);

                JOptionPane.showMessageDialog(
                        this,
                        "Vehículo agregado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                // Limpio los campos para el próximo ingreso
                tfMatriculacion.setText("");
                tfAnio.setText("");
                cbMarca.setSelectedIndex(0);
                cbModelo.setSelectedIndex(0);
            } else {
                // Limpio los campos para el próximo ingreso
                tfMatriculacion.setText("");
                tfAnio.setText("");
                cbMarca.setSelectedIndex(0);
                cbModelo.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_bConfirmarActionPerformed

    private void tfMatriculacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatriculacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatriculacionActionPerformed

    private void cbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaActionPerformed
        String marcaSeleccionada = (String) cbMarca.getSelectedItem();
        VehiculoPersonaController vcp = new VehiculoPersonaController(this);
        vcp.mostrarModelosPorMarcaVistaCrearVehiculo(marcaSeleccionada);
    }//GEN-LAST:event_cbMarcaActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_bCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "¿Estas seguro de cerrar la ventana?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            System.out.println("Se ha cerrado corectamente");
        } else if (confirm == JOptionPane.NO_OPTION) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCrearVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCrearVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbModelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lAnio;
    private javax.swing.JLabel lMarca;
    private javax.swing.JLabel lMatriculacion;
    private javax.swing.JLabel lModelo;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfMatriculacion;
    // End of variables declaration//GEN-END:variables
}
